version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: "${DOCKER_DB_USER}"
      POSTGRES_PASSWORD: "${DOCKER_DB_PASSWORD}"
      POSTGRES_DB: nest
    networks:
      - nbadashboardapi
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: "${DOCKER_DB_USER}"
      POSTGRES_PASSWORD: "${DOCKER_DB_PASSWORD}"
      POSTGRES_DB: nest
    networks:
      - nbadashboardapi
networks:
  nbadashboardapi: